#!/usr/bin/env python
"""
Author: Sunao Sugiyama
"""

import os
import sys
import glob
from pdf2image import convert_from_path

def pdf_to_png(pdf_path):
    png_path = pdf_path.replace('.pdf', '.png')

    # Convert PDF to PNG
    images = convert_from_path(pdf_path)
    
    # Save PNG image(s)
    if len(images) == 1:
        image = images[0]
        image.save(png_path, 'PNG')
    else:
        for i, image in enumerate(images):
            image_path = os.path.splitext(png_path)[0] + f'_{i}.png'
            image.save(image_path, 'PNG')

if __name__ == '__main__':
    re_pdf_path = sys.argv[1]
    for pdf_path in glob.glob(re_pdf_path):
        if not pdf_path[-4:] == '.pdf':
            continue
        pdf_to_png(pdf_path)
