#!/bin/bash
# Author: Sunao Sugiyama

# Get password type argument
password_type=$1

# Check if password type is provided
if [ -z "$password_type" ]; then
    echo "Please provide password type as argument"
    exit 1
fi

# Check if passwords file exists
SCRIPT_DIR=$(cd $(dirname $0); pwd)
passwords_file="${SCRIPT_DIR}/passwords"
if [ ! -f "$passwords_file" ]; then
    echo "Passwords file not found"
    exit 1
fi

# Get password for specified type
password=$(grep "^$password_type:" "$passwords_file" | cut -d ' ' -f 2)

# Check if password is found
if [ -z "$password" ]; then
    echo "Password not found for specified type"
    exit 1
fi

echo "$password"

